# Generated by Django 5.1.4 on 2025-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
