# Generated by Django 5.1.4 on 2025-04-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_payment_method_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment', 'Payment'), ('order', 'Order'), ('alert', 'Alert')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Card')], max_length=20, null=True)),
                ('table_number', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
            ],
        ),
    ]
